-- CRITICAL: This script creates the table needed for the Chart to work.
-- Please run this in Supabase > SQL Editor

create table if not exists action_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable security so only you see your data
alter table action_logs enable row level security;

create policy "Users can view their own action logs"
  on action_logs for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own action logs"
  on action_logs for insert
  with check ( auth.uid() = user_id );

grant all on table action_logs to authenticated;
grant all on table action_logs to service_role;
