-- Create the table for tracking button clicks if it doesn't exist
create table if not exists action_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action_name text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable security (Row Level Security)
alter table action_logs enable row level security;

-- Allow users to see only their own logs
create policy "Users can view their own logs"
  on action_logs for select
  using ( auth.uid() = user_id );

-- Allow users to insert their own logs (record clicks)
create policy "Users can insert their own logs"
  on action_logs for insert
  with check ( auth.uid() = user_id );

-- Grant access to authenticated users
grant all on table action_logs to authenticated;
grant all on table action_logs to service_role;
