-- 1. Create user_balances table (if it doesn't exist)
create table if not exists user_balances (
  user_id uuid references auth.users not null primary key,
  amount numeric not null default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for user_balances
alter table user_balances enable row level security;

-- Policies for user_balances (drop if exists first to avoid errors, or use do block)
drop policy if exists "Users can view their own balance" on user_balances;
create policy "Users can view their own balance" on user_balances for select using ( auth.uid() = user_id );

drop policy if exists "Users can insert their own balance" on user_balances;
create policy "Users can insert their own balance" on user_balances for insert with check ( auth.uid() = user_id );

drop policy if exists "Users can update their own balance" on user_balances;
create policy "Users can update their own balance" on user_balances for update using ( auth.uid() = user_id );

-- 2. Drop the old 'orders' table
drop table if exists orders;

-- 3. (Optional) Ensure hacoo_orders exists (safe creation)
create table if not exists hacoo_orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  order_reference text,
  order_date timestamp with time zone default timezone('utc'::text, now()) not null,
  estimated_commission numeric not null,
  status text not null check (status in ('pending', 'delivered', 'canceled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Note: policies for hacoo_orders are not re-created here to avoid errors if they exist.
