-- Create orders table
create table orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  amount numeric not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table orders enable row level security;

-- Policies
create policy "Users can view their own orders"
  on orders for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own orders"
  on orders for insert
  with check ( auth.uid() = user_id );

create policy "Users can delete their own orders"
  on orders for delete
  using ( auth.uid() = user_id );
