-- Create hacoo_orders table
create table hacoo_orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  order_reference text, -- "le numero de reference" (not displayed but present)
  order_date timestamp with time zone default timezone('utc'::text, now()) not null,
  estimated_commission numeric not null,
  status text not null check (status in ('pending', 'delivered', 'canceled')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table hacoo_orders enable row level security;

-- Policies
create policy "Users can view their own hacoo orders"
  on hacoo_orders for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own hacoo orders" -- Optional, if manual insert needed or via generic API
  on hacoo_orders for insert
  with check ( auth.uid() = user_id );

create policy "Users can update their own hacoo orders"
  on hacoo_orders for update
  using ( auth.uid() = user_id );
