-- Create a table for user stats
create table user_stats (
  user_id uuid references auth.users not null primary key,
  chat_usage_count integer default 0,
  action_usage_count integer default 0,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create specific RLS policies for user_stats
alter table user_stats enable row level security;

create policy "Users can view their own stats"
  on user_stats for select
  using ( auth.uid() = user_id );

create policy "Users can update their own stats"
  on user_stats for update
  using ( auth.uid() = user_id );

create policy "Users can insert their own stats"
  on user_stats for insert
  with check ( auth.uid() = user_id );

-- Create a table for chat messages
create table chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  text text not null,
  sender text not null check (sender in ('user', 'bot')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for chat_messages
alter table chat_messages enable row level security;

create policy "Users can view their own messages"
  on chat_messages for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own messages"
  on chat_messages for insert
  with check ( auth.uid() = user_id );

-- Create a function to handle new user signup
-- This triggers when a new user is created in auth.users
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.user_stats (user_id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function on new user signup
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
